import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import "./globals.css"
import { NavBar } from "@/components/NavBar"
import { ThemeProvider } from "@/components/theme-provider"
import { auth } from "@clerk/nextjs"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const { userId } = await auth()
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body
					className={
						inter.className + " flex flex-col w-full items-center min-h-screen"
					}
				>
					<ThemeProvider>
						<NavBar userId={userId} />
					</ThemeProvider>
					{children}
					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	)
}
